-- DROP TABLE IF EXISTS  ANCHOR;

-- CREATE TABLE ANCHOR (
--     ANCHOR_ID BIGINT GENERATED ALWAYS AS IDENTITY,
--     TITLE TEXT NOT NULL,
--     HREF TEXT NOT NULL,
--     ICON_URL TEXT,
--     ICON TEXT,
--     PARENT BIGINT,
--     PARENT_FOLDER BIGINT,
--     CREATE_DATE TIMESTAMP NOT NULL,
--     MODIFIED_DATE TIMESTAMP NOT NULL,
--     CONSTRAINT PRI_ANCHOR_ID PRIMARY KEY (ANCHOR_ID),
--     CONSTRAINT FOR_ANCHOR_PARENT_ANCHOR_ID FOREIGN KEY (PARENT)
--         REFERENCES ANCHOR(ANCHOR_ID),
--     CONSTRAINT FOR_ANCHOR_PAREND_FOLDER_FORLDER_ID FOREIGN KEY (PARENT_FOLDER)
--         REFERENCES FOLDER(FOLDER_ID));

