CREATE TABLE FOLDER (
    FOLDER_ID IDENTITY NOT NULL,
    FOLDER_NAME CLOB NOT NULL,
    TOOLBAR_FOLDER BOOLEAN,
    PARENT BIGINT,
    CREATE_DATE TIMESTAMP NOT NULL,
    MODIFIED_DATE TIMESTAMP NOT NULL,
    CONSTRAINT PRI_FOLDER_ID PRIMARY KEY (FOLDER_ID),
    CONSTRAINT FOR_FOLDER_PARENT_FOLDER_FOLDER_ID FOREIGN KEY (PARENT)
        REFERENCES FOLDER(FOLDER_ID));
        
CREATE TABLE ANCHOR (
    ANCHOR_ID IDENTITY NOT NULL,
    TITLE CLOB NOT NULL,
    HREF CLOB NOT NULL,
    ICON_URL CLOB,
    ICON CLOB,
    PARENT BIGINT,
    PARENT_FOLDER BIGINT,
    CREATE_DATE TIMESTAMP NOT NULL,
    MODIFIED_DATE TIMESTAMP NOT NULL,
    CONSTRAINT PRI_ANCHOR_ID PRIMARY KEY (ANCHOR_ID),
    CONSTRAINT FOR_ANCHOR_PARENT_ANCHOR_ID FOREIGN KEY (PARENT)
        REFERENCES ANCHOR(ANCHOR_ID),
    CONSTRAINT FOR_ANCHOR_PAREND_FOLDER_FORLDER_ID FOREIGN KEY (PARENT_FOLDER)
        REFERENCES FOLDER(FOLDER_ID));

CREATE TABLE LOGIN (
    LOGIN_ID IDENTITY NOT NULL,
    GUID UUID NOT NULL,
    USERNAME CLOB NOT NULL,
    PASSWORD CLOB NOT NULL,
    DISPLAY_ORIGIN CLOB NOT NULL,
    ORIGIN CLOB NOT NULL,
    HOSTNAME CLOB NOT NULL,
    FORM_ACTION_ORIGIN CLOB NOT NULL,
    FORM_SUBMIT_URL CLOB NOT NULL,
    HTTP_REALM CLOB NOT NULL,
    USERNAME_FIELD CLOB NOT NULL,
    PASSWORD_FIELD CLOB NOT NULL,
    TIME_USED INTEGER NOT NULL,
    CREATE_DATE TIMESTAMP NOT NULL,
    USED_DATE TIMESTAMP NOT NULL,
    PASSWORD_CHANGED TIMESTAMP NOT NULL,
    CONSTRAINT PRI_LOGIN_ID PRIMARY KEY (LOGIN_ID));
